# Generated by Django 2.0.9 on 2018-10-15 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.IntegerField(unique=True, verbose_name='CPF ou CNPJ')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=40, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=40, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('fone', models.IntegerField(verbose_name='Fone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contato', models.CharField(max_length=100, verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='Ccusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
                ('assinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Assinante', verbose_name='Assinante')),
            ],
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Pcontas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('S', 'Sintetica'), ('A', 'Analitica')], default='A', max_length=1, verbose_name='Tipo')),
                ('grupo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Grupo')),
                ('dre', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='DRE')),
            ],
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='Descrição')),
                ('dt_inicio', models.DateField(verbose_name='Data Inicial')),
                ('dt_final', models.DateField(verbose_name='Data Final')),
                ('assinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Assinante', verbose_name='Assinante')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ha_fisico', models.IntegerField(verbose_name='Ha físico')),
                ('assinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Assinante', verbose_name='Assinante')),
            ],
        ),
    ]
